# Generated by Django 5.0.9 on 2024-12-02 12:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('equipment', models.CharField(choices=[('S', 'Seeding'), ('R', 'Research')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('engine_on', models.TimeField(default=django.utils.timezone.now)),
                ('takeoff', models.TimeField(default=django.utils.timezone.now)),
                ('landing', models.TimeField(default=django.utils.timezone.now)),
                ('engine_off', models.TimeField(default=django.utils.timezone.now)),
                ('ej_attempted', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(306)])),
                ('ej_fired', models.PositiveSmallIntegerField(default=0)),
                ('bip_attempted', models.PositiveSmallIntegerField(default=0)),
                ('bip_fired', models.PositiveSmallIntegerField(default=0)),
                ('hygro_attempted', models.PositiveSmallIntegerField(default=0)),
                ('hygro_fired', models.PositiveSmallIntegerField(default=0)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.mission')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.plane')),
            ],
        ),
    ]
