# Generated by Django 5.0.9 on 2024-11-07 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('aircraft', models.CharField(max_length=6)),
                ('engine_on', models.TimeField()),
                ('take_off', models.TimeField()),
                ('landing', models.TimeField()),
                ('ej', models.PositiveIntegerField()),
                ('bip', models.PositiveIntegerField()),
                ('hygro', models.PositiveIntegerField()),
                ('mission_type', models.CharField(max_length=10)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
