# Generated by Django 5.0.9 on 2024-12-02 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='air_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
