# Generated by Django 5.0.9 on 2024-11-07 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_engine_on_alter_flight_landing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='engine_off',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
