# Generated by Django 5.0.9 on 2024-12-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_flight_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flights.airport'),
        ),
    ]
