# Generated by Django 5.0.9 on 2024-12-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='hygro_attempted',
            new_name='hbip_attempted',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='hygro_fired',
            new_name='hbip_fired',
        ),
    ]
