# Generated by Django 5.0.9 on 2024-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_flight_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='bip',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ej',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='hygro',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
