# Generated by Django 5.0.9 on 2024-12-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_flight_dest_alter_flight_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='bip_attempted',
            new_name='bip_att',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='hbip_attempted',
            new_name='hbip_att',
        ),
    ]
