# Generated by Django 5.0.9 on 2024-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flight_bip_alter_flight_ej_alter_flight_hygro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='bip',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='ej',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='hygro',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
