# Generated by Django 5.0.9 on 2024-12-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_rename_bip_attempted_flight_bip_att_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='ej_attempted',
            new_name='ej_att',
        ),
    ]
