# Generated by Django 5.0.9 on 2024-11-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_flight_bip_alter_flight_ej_alter_flight_hygro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aircfaft',
            new_name='Aircraft',
        ),
    ]
