# Generated by Django 5.0.9 on 2024-12-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_rename_ej_attempted_flight_ej_att'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.airport'),
        ),
    ]
