# Generated by Django 5.0.9 on 2024-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_rename_aircfaft_aircraft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='bip',
            new_name='bip_att',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='ej',
            new_name='bip_fired',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='hygro',
            new_name='ej_att',
        ),
        migrations.AddField(
            model_name='flight',
            name='ej_fired',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='hygro_att',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='hygro_fired',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
