# Generated by Django 5.0.9 on 2024-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_flight_base_alter_flight_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='bip_dud',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='bip_mis',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='ej_dud',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='ej_mis',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='hbip_dud',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='hbip_mis',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
