# Generated by Django 5.0.9 on 2024-11-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_rename_bip_flight_bip_att_rename_ej_flight_bip_fired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='bip_att',
            new_name='bip_attempted',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='ej_att',
            new_name='ej_attempted',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='hygro_att',
            new_name='hygro_attempted',
        ),
    ]
