# Generated by Django 5.0.9 on 2024-11-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_rename_bip_att_flight_bip_attempted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aircraft',
            new_name='Plane',
        ),
    ]
