# Generated by Django 5.0.9 on 2024-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_airport_iata_airport_icao_airport_is_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='IATA code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='ICAO code'),
        ),
    ]
