# Generated by Django 5.0.9 on 2024-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_rename_aircraft_plane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='aircraft',
            new_name='plane',
        ),
    ]
