# Generated by Django 5.0.9 on 2024-12-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_airport_iata_alter_airport_icao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='IATA code'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='ICAO code'),
        ),
    ]
