# Generated by Django 5.0.9 on 2024-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_rename_aircraft_flight_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plane',
            name='year_in_school',
            field=models.CharField(choices=[('S', 'Seeding'), ('R', 'Research')], default='S', max_length=1),
        ),
    ]
