# Generated by Django 5.0.9 on 2024-11-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_plane_type_plane_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='year_in_school',
            new_name='equipment',
        ),
    ]
