# Generated by Django 5.0.9 on 2024-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_alter_airport_iata_alter_airport_icao'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='targets',
            field=models.ManyToManyField(related_name='targets', to='flights.airport'),
        ),
    ]
