# Generated by Django 5.0.9 on 2024-11-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_rename_year_in_school_plane_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='pilot',
        ),
    ]
