# Generated by Django 5.0.9 on 2024-12-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_pilot_alter_flight_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='copilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_copilot', to='flights.pilot'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_pilot', to='flights.pilot'),
        ),
    ]
