# Generated by Django 5.0.9 on 2024-11-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_flight_pilot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='take_off',
            new_name='takeoff',
        ),
    ]
