# Generated by Django 5.0.9 on 2024-12-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_flight_copilot_alter_flight_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='copilot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_copilot', to='flights.pilot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_as_pilot', to='flights.pilot'),
        ),
    ]
