# Generated by Django 5.0.9 on 2024-12-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='targets',
        ),
        migrations.AddField(
            model_name='flight',
            name='targets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.target'),
        ),
    ]
