# Generated by Django 5.0.9 on 2024-12-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_remove_flight_targets_flight_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='is_target',
        ),
        migrations.AlterField(
            model_name='plane',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
