# Generated by Django 5.0.9 on 2024-12-19 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_remove_airport_is_target_alter_plane_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest', to='flights.airport'),
        ),
    ]
