# Generated by Django 5.0.9 on 2025-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0023_missiontype_alter_flight_mission_type_delete_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontype',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterModelTable(
            name='missiontype',
            table=None,
        ),
    ]
